### ISSUE TITLE
Console is showing blank, I was using v0.5.004 it working good. but i tries to run v.6.*.* it does not shpwing anything. It shows blank home page. plz find the following screenshot  https://Amittri.tinytake.com/msc/OTg1MDMxMV8yMzUwNTU3OQ

### ISSUE THREAD

**Issue by 03amittrivedi** [mihemihe/myADMonitor#4]

**Comment by 03amittrivedi** [comment]
Hi
Plz do the needful asap

**Comment by mihemihe** [comment]
That screenshot is what is shown right after starting the application because there are no changes.  Check the cmd console where the backend application is running and change something in your Active Directory (create a test user, or change an attribute), the next delta should capture the change and show it in the frontend. 

Regarding the releases, the old 0.5 is available for download, but I recommend using the latest 0.6 because there are a lot of new changes.

Edit: Given that it does not show anything on the statistics, it may not be able to contact a Domain Controller. Check the cmd of the backend to see if the tool had any issue connecting to Active Directory

**Comment by 03amittrivedi** [comment]
Hi
Thanks for your kind response.

I would like to update you that i had already changed many attributes like change the password, create many users, delete some old users, but still it is not showing any records.

As for as AD Connectivy is concern, old version (0.5) is working (Even i have installed this tool on DC), so i think there will be no issue for connectivity.
if anything else required, i will follow your step

Thanks

**Comment by mihemihe** [comment]
I need to see what is showing on the cmd of the backend. When the tool opens, the cmd shows the initialization and the deltas. Give me the text that appears there, and let me know if the deltas are running every 5 seconds. Thanks

**Comment by 03amittrivedi** [comment]
Hello
Thanks for showing your interest
I have created the AD user with name test100 & test1001 but still no output is showing at adMonitor console.
Plz find the following screesnshot for your kind reference.
https://Amittri.tinytake.com/msc/OTg2NjU2Ml8yMzUyNDY3Ng

Thanks

**Comment by mihemihe** [comment]
mmmh.... few things that come to my mind:

- Can you try to download Chrome and test it in Chrome
- I see the cache was built correctly, and it is tracking 230 objects, did you do any change on the config.ini file?
- When there is a change, the tool creates a log file in the same folder, is the log file being created in your folder, is there any content on it?
- Press F12, and go to the Console section. Is there any error, or it shows the queries being executed every few seconds. Something like this: https://i.imgur.com/SXL3KEo.png

**Comment by mihemihe** [comment]
Additionally to my post above, could you also share with me the version of Windows your DC is running? Based on the picture, I guess it is 2012 or 2012

**Comment by 03amittrivedi** [comment]
Hi
Sorry for delay response
On DC we are using server 2012 R2 & chrome . localhost:5000 myADmonitor console is opening & changes are reflecting. Firewall is OFF in this machine (DC).

But on other machine that is running with WINDOWS 10 pro using same browser (Chrome) console is blank.
Screenshot is here-
https://Amittri.tinytake.com/msc/OTg5NTg3OF8yMzU1NzgyMQ

Thanks for kind help

**Comment by mihemihe** [comment]
Thanks for the feedback, that helps a lot to pinpoint the issue. So to summarize, it is running fine on the DC, but when you try to connect to that running instance on the DC from another computer, you do not see any update, right?

Press F12, and go to the Console section. Is there iany error, or it shows the queries being executed every few seconds.? Something like this: https://i.imgur.com/SXL3KEo.png

**Comment by mihemihe** [comment]
> Hi Sorry for delay response On DC we are using server 2012 R2 & chrome . localhost:5000 myADmonitor console is opening & changes are reflecting. Firewall is OFF in this machine (DC).
> 
> But on other machine that is running with WINDOWS 10 pro using same browser (Chrome) console is blank. Screenshot is here- https://Amittri.tinytake.com/msc/OTg5NTg3OF8yMzU1NzgyMQ
> 
> Thanks for kind help

I found the issue. For some reason I left the dev testing configuration on the release, so the url has "localhost" hardcoded. 

I will fix it tomorrow and create a 0.6.1 release. Thanks !

**Comment by 03amittrivedi** [comment]
Hi,
Thanks for showing your intrest in this issue.

As suggested i hv captured the console screensshot on Windows10 pro machine (Defender firewall is off on DC )
https://Amittri.tinytake.com/msc/OTkwNzYyNF8yMzU3MDQ4OQ

Note- 1. On DC (Server 2012 R2) on chrome it is working & records are reflecting
          2. Firewall is off on both machine. (Records are even refelecting  on the DC after enableing firewall )
              On DC (Server 2012 R2)  Screenshot-
              https://Amittri.tinytake.com/msc/OTkwNzY4Ml8yMzU3MDU0Nw

          3. Here i have used Google Chrome on both machine
          

Thnaks

**Comment by 03amittrivedi** [comment]
Hi,
Can we have any update?

**Comment by mihemihe** [comment]
Thursday 1st I will have time to work on it and I will release the fixed version. Is a quick fix, but I am not online these days.

**Comment by 03amittrivedi** [comment]
Hi,
I am waiting very anxiety for your kind response.

**Comment by 03amittrivedi** [comment]
Still showing no response. I think you dont have interest in this tool.

**Comment by ButlerKevinD** [comment]
> Still showing no response. I think you dont have interest in this tool.

I'm certain the author has other things to do in addition to updating this application. Either utilize v0.5 or wait until he can publish v0.6.1. Whining about it won't get it published any sooner.

**Comment by 03amittrivedi** [comment]
> I'm certain the author has other things to do in addition to updating this application. Either utilize v0.5 or wait until he can publish v0.6.1. Whining about it won't get it published any sooner.

Thanks for your kind prompt.
I'm sorry if you feel hurt. So Sorry for this.
I will wait for your next update.

Thanks

**Comment by 03amittrivedi** [comment]
Hi
I hope you are doing well. May i know any progress in this issue?

**Comment by mihemihe** [comment]
> Hi I hope you are doing well. May i know any progress in this issue?

I have fixed the issue and released a new version. You can get it here: https://github.com/mihemihe/myADMonitor/releases/tag/v0.6Fix1

Let me know if it works. 

Very important, make sure to refresh the browser at least once using CTRL + F5 , otherwise it may take the cached version.

**Comment by 03amittrivedi** [comment]
Thank you so much Mihemihe,

It working good. I appreciate your efforts.

Could you plz let me know how can i change UTC to IST. we need the display info in IST.

I will be highly obliged to you

Thanks

**Comment by 03amittrivedi** [comment]
Hi
Its working nice 
could you plz increase the font size & utilize the blank space at right (as shows in the below screenshot).
it could be more easier if you able to proivde filter option at console
https://Amittri.tinytake.com/msc/MTAwNzIzNjhfMjM3NDQ2Mjk

Thanks

**Comment by mihemihe** [comment]
> Hi Its working nice could you plz increase the font size & utilize the blank space at right (as shows in the below screenshot). it could be more easier if you able to proivde filter option at console https://Amittri.tinytake.com/msc/MTAwNzIzNjhfMjM3NDQ2Mjk
> 
> Thanks

I tested different font sizes on multiple resolutions and DPI and it is hard to find a value that fits for everybody. The space on the right is intended, because sometimes there are very long strings (for instance changing a DN on a very long path). I think the best option in your case is to CTRL + Mouse Wheel to increase the zoom when you open it. 

As of now, the only filter via console is the LDAP filter on the config file, which is quite versatile. With a properly crafted LDAP query you can achieve the same than with the filters on the UI. If you tell me the filter you required I can create the LDAP filter for you.

**Comment by 03amittrivedi** [comment]
Hi
Thank you so much for your kind attention regarding my query.

As for as Filter option is concern, suppose we would like to see attributes like "pwdlastset" since last 24 hours. how can we do it.
Is there any way to automate the sending mail this report (CSV) with redefinedColumn in every 24 hours.

if you could able to prive this i will be highly obliged to you.

Thanks
